//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAccesoPROBCA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        /*TEST*/
        //[global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=192.168.1.4;Initial Catalog=AccesoSteelgo-Vigilancia;MultipleActiveResultSets=True;User ID=accesosteelgo;Password=123$PROBCA")]
        /*PRODUCCION*/
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=192.168.1.13\SAM3;Initial Catalog=AccesoSteelgo-Vigilancia;MultipleActiveResultSets=True;User ID=sam;Password=sam123!")]
        /*LOCAL*/
        //[global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=DESKTOP-TCCMQI0\SAM3;Initial Catalog=AccesoSteelgo-Vigilancia;MultipleActiveResultSets=True;User ID=sa;Password=maftec09")]        
        public string conexionproyectoid
        {
            get
            {
                return ((string)(this["conexionproyectoid"]));
            }
        }
    }
}
